import "../resources/styles/globals.scss";

import { Inter } from "next/font/google";
import Navbar from "../components/layout/navbar.jsx";
import Footer from "../components/layout/footer.jsx";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="bg-background text-white scroll-smooth">
      <body className={inter.className}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
